#!/bin/sh

echo "Reloading Library Database"
ldconfig

if ! grep -q "MYCROFT_START_CMD" /etc/environment ; then
	echo "Disabling mycroft startup from gui"
	echo "MYCROFT_START_CMD=sleep 10" >> /etc/environment
fi

if ! grep -q "MYCROFT_STOP_CMD" /etc/environment ; then
	echo "Disabling mycroft stop from gui"
	echo "MYCROFT_STOP_CMD=sleep 10" >> /etc/environment
fi

#echo "Restarting display service"
systemctl enable mycroft-messagebus
systemctl enable mycroft-voice
systemctl enable mycroft-skills
systemctl enable mycroft-enclosure
systemctl enable mycroft-audio
systemctl enable mycroft

mycroft-pip install sdnotify

#systemctl stop mycroft
#systemctl stop sddm
#systemctl start sddm
#systemctl start mycroft
