#!/usr/bin/env bash

LOG_DIR=/var/log/mycroft

mycroft-messagebus &>> $LOG_DIR/bus.log &
mycroft-skills &>> $LOG_DIR/skills.log &
mycroft-speech-client &>> $LOG_DIR/voice.log &
mycroft-audio &>> $LOG_DIR/audio.log &
mycroft-enclosure-client &>> $LOG_DIR/enclosure.log &
sleep 10
