#!/usr/bin/env sh

mycroft-messagebus & >> /var/log/mycorft/bus.log
mycroft-skills & >> /var/log/mycroft/skills.log
mycroft-speech-client & >> /var/log/mycroft/voice.log
mycroft-audio & >> /var/log/mycroft/audio.log
mycroft-enclosure-client & >> /var/log/mycroft/enclosure.log
sleep 10
