#! /usr/bin/env bash

safe_kill() {
	kill -2 "$1" # SIGINT
	for i in $(seq 1 1 20)
	do
		sleep 0.1
		! kill -0 "$1" > /dev/null 2>&1 && break
	done || kill -9 "$1" # SIGKILL
}

function find_and_kill() {
	cmd=$(which $1)
	for pid in $(pgrep -f $cmd); do
		echo "Stopping $1 ($pid)"
		safe_kill $pid
	done
}


find_and_kill mycroft-skills
find_and_kill mycroft-audio
find_and_kill mycroft-enclosure-client
find_and_kill mycroft-speech-client
find_and_kill mycroft-messagebus

